[package]
name = "fist"
version = "0.1.0"
authors = ["TheNappap <napoleonpapiertjes@gmail.com>"]
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = "0.6"

[[bench]]
name = "benches"
html_reports = true
harness = false
