[package]
name = "fist"
version = "0.1.0"
authors = ["mathijsd <napoleonpapiertjes@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benches"
harness = false
